

# Android
export ANDROID_HOME="/Users/lbo/Library/Android/sdk"
export ANDROID_NDK="/usr/local/opt/android-ndk"
export PATH="$ANDROID_HOME/platform-tools:$PATH"
export PATH="$ANDROID_HOME/tools:$PATH"